# Generated by Django 4.1.7 on 2023-05-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trainer_class', models.CharField(max_length=255, verbose_name='Class')),
                ('pokemon1', models.CharField(max_length=255, verbose_name='Pkmn1')),
                ('pokemon2', models.CharField(max_length=255, verbose_name='Pkmn2')),
                ('pokemon3', models.CharField(max_length=255, verbose_name='Pkmn3')),
                ('pokemon4', models.CharField(max_length=255, verbose_name='Pkmn4')),
                ('pokemon5', models.CharField(max_length=255, verbose_name='Pkmn5')),
                ('pokemon6', models.CharField(max_length=255, verbose_name='Pkmn6')),
            ],
        ),
    ]
